run:
  timeout: 5m

linters:
  enable:
    # Default linters (keep enabled)
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Code quality
    - gocritic
    - revive
    - unconvert
    - unparam
    - goconst

    # Error handling
    - errorlint
    - nilerr

    # Performance
    - prealloc

    # Security
    - gosec

    # HTTP
    - bodyclose

    # Testing
    - testifylint

    # Bugs
    - copyloopvar
    - durationcheck
    - misspell

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
    disabled-checks:
      - hugeParam  # Too noisy for this codebase

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true  # Not needed for internal packages
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

  goconst:
    min-len: 3
    min-occurrences: 3

  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
      - G304  # File path from variable (needed for file operations)
      - G306  # WriteFile permissions (config files should be 0644)

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  testifylint:
    enable-all: true

  misspell:
    locale: US

issues:
  exclude-rules:
    # Allow dot imports for testify in tests
    - path: _test\.go
      linters:
        - revive
      text: "dot-imports"

    # Test files can have longer functions
    - path: _test\.go
      linters:
        - gocritic
      text: "hugeParam"

    # Generated files
    - path: mocks/
      linters:
        - revive
        - gocritic

  max-issues-per-linter: 0
  max-same-issues: 0
