version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build both binaries
    cmds:
      - go build -o arrgo ./cmd/arrgo
      - go build -o arrgod ./cmd/arrgod

  build:client:
    desc: Build CLI client only
    cmds:
      - go build -o arrgo ./cmd/arrgo

  build:server:
    desc: Build server daemon only
    cmds:
      - go build -o arrgod ./cmd/arrgod

  run:
    desc: Run the server
    deps: [build:server]
    cmds:
      - ./arrgod

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  test:v:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report: coverage.html"

  test:integration:
    desc: Run integration tests
    cmds:
      - go test -tags=integration -v ./internal/api/v1/

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - gofmt -w .
      - goimports -w .

  check:
    desc: Run all checks (fmt, lint, test)
    cmds:
      - task: fmt
      - task: lint
      - task: test

  dev:
    desc: Run server with live reload (requires air)
    cmds:
      - air

  generate:
    desc: Run go generate
    cmds:
      - go generate ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f arrgo arrgod coverage.out coverage.html
      - rm -rf tmp/

  deps:
    desc: Download dependencies
    cmds:
      - go mod download
      - go mod tidy
