// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmunix/arrgo/internal/api/v1 (interfaces: Searcher,DownloadManager,PlexClient,FileImporter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/vmunix/arrgo/internal/api/v1 Searcher,DownloadManager,PlexClient,FileImporter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	download "github.com/vmunix/arrgo/internal/download"
	importer "github.com/vmunix/arrgo/internal/importer"
	search "github.com/vmunix/arrgo/internal/search"
	gomock "go.uber.org/mock/gomock"
)

// MockSearcher is a mock of Searcher interface.
type MockSearcher struct {
	ctrl     *gomock.Controller
	recorder *MockSearcherMockRecorder
	isgomock struct{}
}

// MockSearcherMockRecorder is the mock recorder for MockSearcher.
type MockSearcherMockRecorder struct {
	mock *MockSearcher
}

// NewMockSearcher creates a new mock instance.
func NewMockSearcher(ctrl *gomock.Controller) *MockSearcher {
	mock := &MockSearcher{ctrl: ctrl}
	mock.recorder = &MockSearcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearcher) EXPECT() *MockSearcherMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSearcher) Search(ctx context.Context, q search.Query, profile string) (*search.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, q, profile)
	ret0, _ := ret[0].(*search.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearcherMockRecorder) Search(ctx, q, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearcher)(nil).Search), ctx, q, profile)
}

// MockDownloadManager is a mock of DownloadManager interface.
type MockDownloadManager struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadManagerMockRecorder
	isgomock struct{}
}

// MockDownloadManagerMockRecorder is the mock recorder for MockDownloadManager.
type MockDownloadManagerMockRecorder struct {
	mock *MockDownloadManager
}

// NewMockDownloadManager creates a new mock instance.
func NewMockDownloadManager(ctrl *gomock.Controller) *MockDownloadManager {
	mock := &MockDownloadManager{ctrl: ctrl}
	mock.recorder = &MockDownloadManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadManager) EXPECT() *MockDownloadManagerMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockDownloadManager) Cancel(ctx context.Context, downloadID int64, deleteFiles bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, downloadID, deleteFiles)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockDownloadManagerMockRecorder) Cancel(ctx, downloadID, deleteFiles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockDownloadManager)(nil).Cancel), ctx, downloadID, deleteFiles)
}

// Client mocks base method.
func (m *MockDownloadManager) Client() download.Downloader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(download.Downloader)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockDownloadManagerMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockDownloadManager)(nil).Client))
}

// GetActive mocks base method.
func (m *MockDownloadManager) GetActive(ctx context.Context) ([]*download.ActiveDownload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActive", ctx)
	ret0, _ := ret[0].([]*download.ActiveDownload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActive indicates an expected call of GetActive.
func (mr *MockDownloadManagerMockRecorder) GetActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActive", reflect.TypeOf((*MockDownloadManager)(nil).GetActive), ctx)
}

// MockPlexClient is a mock of PlexClient interface.
type MockPlexClient struct {
	ctrl     *gomock.Controller
	recorder *MockPlexClientMockRecorder
	isgomock struct{}
}

// MockPlexClientMockRecorder is the mock recorder for MockPlexClient.
type MockPlexClientMockRecorder struct {
	mock *MockPlexClient
}

// NewMockPlexClient creates a new mock instance.
func NewMockPlexClient(ctrl *gomock.Controller) *MockPlexClient {
	mock := &MockPlexClient{ctrl: ctrl}
	mock.recorder = &MockPlexClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlexClient) EXPECT() *MockPlexClientMockRecorder {
	return m.recorder
}

// FindSectionByName mocks base method.
func (m *MockPlexClient) FindSectionByName(ctx context.Context, name string) (*importer.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSectionByName", ctx, name)
	ret0, _ := ret[0].(*importer.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSectionByName indicates an expected call of FindSectionByName.
func (mr *MockPlexClientMockRecorder) FindSectionByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSectionByName", reflect.TypeOf((*MockPlexClient)(nil).FindSectionByName), ctx, name)
}

// GetIdentity mocks base method.
func (m *MockPlexClient) GetIdentity(ctx context.Context) (*importer.Identity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIdentity", ctx)
	ret0, _ := ret[0].(*importer.Identity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIdentity indicates an expected call of GetIdentity.
func (mr *MockPlexClientMockRecorder) GetIdentity(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIdentity", reflect.TypeOf((*MockPlexClient)(nil).GetIdentity), ctx)
}

// GetLibraryCount mocks base method.
func (m *MockPlexClient) GetLibraryCount(ctx context.Context, sectionKey string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLibraryCount", ctx, sectionKey)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLibraryCount indicates an expected call of GetLibraryCount.
func (mr *MockPlexClientMockRecorder) GetLibraryCount(ctx, sectionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLibraryCount", reflect.TypeOf((*MockPlexClient)(nil).GetLibraryCount), ctx, sectionKey)
}

// GetSections mocks base method.
func (m *MockPlexClient) GetSections(ctx context.Context) ([]importer.Section, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSections", ctx)
	ret0, _ := ret[0].([]importer.Section)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSections indicates an expected call of GetSections.
func (mr *MockPlexClientMockRecorder) GetSections(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSections", reflect.TypeOf((*MockPlexClient)(nil).GetSections), ctx)
}

// HasMovie mocks base method.
func (m *MockPlexClient) HasMovie(ctx context.Context, title string, year int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasMovie", ctx, title, year)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasMovie indicates an expected call of HasMovie.
func (mr *MockPlexClientMockRecorder) HasMovie(ctx, title, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasMovie", reflect.TypeOf((*MockPlexClient)(nil).HasMovie), ctx, title, year)
}

// ListLibraryItems mocks base method.
func (m *MockPlexClient) ListLibraryItems(ctx context.Context, sectionKey string) ([]importer.PlexItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLibraryItems", ctx, sectionKey)
	ret0, _ := ret[0].([]importer.PlexItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLibraryItems indicates an expected call of ListLibraryItems.
func (mr *MockPlexClientMockRecorder) ListLibraryItems(ctx, sectionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLibraryItems", reflect.TypeOf((*MockPlexClient)(nil).ListLibraryItems), ctx, sectionKey)
}

// RefreshLibrary mocks base method.
func (m *MockPlexClient) RefreshLibrary(ctx context.Context, sectionKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshLibrary", ctx, sectionKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshLibrary indicates an expected call of RefreshLibrary.
func (mr *MockPlexClientMockRecorder) RefreshLibrary(ctx, sectionKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshLibrary", reflect.TypeOf((*MockPlexClient)(nil).RefreshLibrary), ctx, sectionKey)
}

// ScanPath mocks base method.
func (m *MockPlexClient) ScanPath(ctx context.Context, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScanPath", ctx, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanPath indicates an expected call of ScanPath.
func (mr *MockPlexClientMockRecorder) ScanPath(ctx, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanPath", reflect.TypeOf((*MockPlexClient)(nil).ScanPath), ctx, filePath)
}

// Search mocks base method.
func (m *MockPlexClient) Search(ctx context.Context, query string) ([]importer.PlexItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].([]importer.PlexItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockPlexClientMockRecorder) Search(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockPlexClient)(nil).Search), ctx, query)
}

// TranslateToLocal mocks base method.
func (m *MockPlexClient) TranslateToLocal(path string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateToLocal", path)
	ret0, _ := ret[0].(string)
	return ret0
}

// TranslateToLocal indicates an expected call of TranslateToLocal.
func (mr *MockPlexClientMockRecorder) TranslateToLocal(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateToLocal", reflect.TypeOf((*MockPlexClient)(nil).TranslateToLocal), path)
}

// MockFileImporter is a mock of FileImporter interface.
type MockFileImporter struct {
	ctrl     *gomock.Controller
	recorder *MockFileImporterMockRecorder
	isgomock struct{}
}

// MockFileImporterMockRecorder is the mock recorder for MockFileImporter.
type MockFileImporterMockRecorder struct {
	mock *MockFileImporter
}

// NewMockFileImporter creates a new mock instance.
func NewMockFileImporter(ctrl *gomock.Controller) *MockFileImporter {
	mock := &MockFileImporter{ctrl: ctrl}
	mock.recorder = &MockFileImporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileImporter) EXPECT() *MockFileImporterMockRecorder {
	return m.recorder
}

// Import mocks base method.
func (m *MockFileImporter) Import(ctx context.Context, downloadID int64, downloadPath string) (*importer.ImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, downloadID, downloadPath)
	ret0, _ := ret[0].(*importer.ImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockFileImporterMockRecorder) Import(ctx, downloadID, downloadPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockFileImporter)(nil).Import), ctx, downloadID, downloadPath)
}
