package release

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

// goldenCases contains curated test cases from real releases to validate parser behavior.
// Each case tests specific patterns and combinations found in the wild.
var goldenCases = []struct {
	name       string
	input      string
	resolution Resolution
	source     Source
	codec      Codec
	hdr        HDRFormat
	audio      AudioCodec
	isRemux    bool
	edition    string
	title      string
	year       int
	group      string
	service    string
	proper     bool
	repack     bool
}{
	// === Resolution Variants (10 cases) ===
	{
		name:       "720p BluRay standard",
		input:      "Jane.Eyre.1996.720p.BluRay.DD.2.0.x264-playHD",
		resolution: Resolution720p,
		source:     SourceBluRay,
		codec:      CodecX264,
		// NOTE: DD.2.0 is not detected as AC3 because parser looks for dd5, dd2, dd7 patterns
		// audio:      AudioAC3,
		title: "Jane Eyre",
		year:  1996,
		group: "playHD",
	},
	{
		name:       "720p WEB-DL",
		input:      "The.Secret.Life.of.Pets.2.2019.720p.TUBI.WEB-DL.AAC.2.0.H.264-PiRaTeS",
		resolution: Resolution720p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAAC,
		title:      "The Secret Life of Pets 2",
		year:       2019,
		group:      "PiRaTeS",
	},
	{
		name:       "1080p BluRay standard",
		input:      "The.Rock.1996.BluRay.1080p.DDP.5.1.x264-hallowed",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "The Rock",
		year:       1996,
		group:      "hallowed",
	},
	{
		name:       "1080p WEB-DL Netflix",
		input:      "Murder.Mystery.2019.1080p.Netflix.WEB-DL.AVC.DDP.5.1-DBTV",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Murder Mystery",
		year:       2019,
		group:      "DBTV",
		service:    "Netflix",
	},
	{
		name:       "2160p UHD BluRay",
		input:      "Knowing.2009.2160p.UHD.BluRay.TrueHD.7.1.Atmos.DV.HDR.x265-RandomBytes",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Knowing",
		year:       2009,
		group:      "RandomBytes",
	},
	{
		name:       "2160p WEB-DL",
		input:      "Doctor.Strange.2016.2160p.DSNP.WEB-DL.H.265.DV.DDP5.1.Atmos-AilMWeb",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Doctor Strange",
		year:       2016,
		group:      "AilMWeb",
		service:    "Disney+",
	},
	{
		name:       "4K marker (maps to 2160p)",
		input:      "Life.Gamble.1978.WEB-DL.4K.H.265.AAC-PTerWEB",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		audio:      AudioAAC,
		title:      "Life Gamble",
		year:       1978,
		group:      "PTerWEB",
	},
	{
		name:       "UHD marker (maps to 2160p)",
		input:      "One.Battle.After.Another.2025.2160p.USA.UHD.Blu-ray.DV.HDR.HEVC.TrueHD.7.1.Atmos-BreezeSunny",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "One Battle After Another",
		year:       2025,
		group:      "BreezeSunny",
	},
	{
		name:       "2160p Complete UHD Blu-ray",
		input:      "The.Gambler.1974.2160p.Complete.UHD.Blu-ray.DV.HDR.HEVC.DTS-HD.MA.1.0-BLoz",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		title:      "The Gambler",
		year:       1974,
		group:      "BLoz",
	},
	{
		name:       "Resolution in middle of name",
		input:      "The.Substance.2024.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "The Substance",
		year:       2024,
		group:      "FraMeSToR",
	},

	// === Source Variants (15 cases) ===
	{
		name:       "BluRay standard",
		input:      "The.Swimmer.1968.BluRay.1080p.DTS-HD.MA.1.0.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "The Swimmer",
		year:       1968,
		group:      "FraMeSToR",
	},
	{
		name:       "Blu-ray hyphenated",
		input:      "Bad.Day.at.Black.Rock.1955.WAC.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.2.0-g0bbles",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Bad Day at Black Rock",
		year:       1955,
		group:      "g0bbles",
	},
	{
		name:       "BDRip variant",
		input:      "The.Monkey.2025.1080p.BDRip.DDP5.1.x265-Vialle",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "The Monkey",
		year:       2025,
		group:      "Vialle",
	},
	{
		name:       "BRRip variant",
		input:      "wick.is.pain.2025.720p.brrip.h264-jff",
		resolution: Resolution720p,
		source:     SourceBluRay,
		codec:      CodecX264,
		title:      "wick is pain",
		year:       2025,
		group:      "jff",
	},
	{
		name:       "WEB-DL standard",
		input:      "The.Terminator.1984.1080p.PCOK.WEB-DL.DDP.5.1.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "The Terminator",
		year:       1984,
		group:      "PiRaTeS",
		service:    "Peacock",
	},
	{
		name:       "WEBDL no hyphen",
		input:      "h-town.2023.1080p.pcok.web-dl.aac.2.0.264-onlyweb",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		audio:      AudioAAC,
		title:      "h-town",
		year:       2023,
		group:      "onlyweb",
		service:    "Peacock",
	},
	{
		name:       "WEBRip standard",
		input:      "Final.Analysis.1992.1080p.WEBRip.DD2.0.x264-NTb",
		resolution: Resolution1080p,
		source:     SourceWEBRip,
		codec:      CodecX264,
		audio:      AudioAC3,
		title:      "Final Analysis",
		year:       1992,
		group:      "NTb",
	},
	{
		name:       "WEBRip with 10bit H.265",
		input:      "The.Retreat.2025.1080p.WEBRip.DDP.2.0.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceWEBRip,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "The Retreat",
		year:       2025,
		group:      "iVy",
	},
	{
		name:       "HDTV standard",
		input:      "supercars.2017.race.23.sandown.race.1080p.feed.x264hi10-lightspeed",
		resolution: Resolution1080p,
		codec:      CodecX264,
		title:      "supercars",
		year:       2017,
		group:      "lightspeed",
	},
	{
		name:       "iTunes WEB-DL",
		input:      "Killer.Whale.2026.2160p.iTunes.WEB-DL.HEVC.10bit.DV.DD5.1.2Audios-QHstudIo",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAC3,
		title:      "Killer Whale",
		year:       2026,
		group:      "QHstudIo",
		// NOTE: iTunes detection requires ".it." delimiter, not matched here
		// service:    "iT",
	},
	{
		name:       "Amazon WEB-DL",
		input:      "Tyler.Perrys.Madeas.Tough.Love.2015.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Tyler Perrys Madeas Tough Love",
		year:       2015,
		group:      "FLUX",
		service:    "Amazon",
	},
	{
		name:       "Hybrid source",
		input:      "The.Great.Train.Robbery.1978.BluRay.1080p.DTS-HD.MA.5.1.AVC.HYBRID.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "The Great Train Robbery",
		year:       1978,
		group:      "FraMeSToR",
	},
	{
		name:       "Criterion Collection Blu-ray",
		input:      "Birth.2004.1080p.Criterion.Collection.Blu-ray.AVC.DTS-HD.MA.5.1-DIYUBits",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		edition:    "Criterion",
		title:      "Birth",
		year:       2004,
		group:      "DIYUBits",
	},
	{
		name:       "GBR region BluRay",
		input:      "March.of.the.Penguins.2.The.Next.Step.2017.GBR.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "March of the Penguins 2 The Next Step",
		year:       2017,
		group:      "FraMeSToR",
	},
	{
		name:       "USA region UHD Blu-ray",
		input:      "She.Killed.in.Ecstasy.1971.2160p.USA.UHD.Blu-ray.HEVC.DTS-HD.MA.2.0",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioDTSHD,
		title:      "She Killed in Ecstasy",
		year:       1971,
	},
	{
		name:   "CAM source",
		input:  "Movie.2025.CAM.x264-GROUP",
		source: SourceCAM,
		codec:  CodecX264,
		title:  "Movie",
		year:   2025,
		group:  "GROUP",
	},
	{
		name:   "HDCAM source",
		input:  "Movie.2025.HDCAM.x264-GROUP",
		source: SourceCAM,
		codec:  CodecX264,
		title:  "Movie",
		year:   2025,
		group:  "GROUP",
	},
	{
		name:       "CAMRip source",
		input:      "Movie.2025.720p.CAMRip.x264-GROUP",
		resolution: Resolution720p,
		source:     SourceCAM,
		codec:      CodecX264,
		title:      "Movie",
		year:       2025,
		group:      "GROUP",
	},
	{
		name:   "Telesync TS source",
		input:  "Movie.2025.TS.x264-GROUP",
		source: SourceTelesync,
		codec:  CodecX264,
		title:  "Movie",
		year:   2025,
		group:  "GROUP",
	},
	{
		name:   "HDTS source",
		input:  "Movie.2025.HDTS.x264-GROUP",
		source: SourceTelesync,
		codec:  CodecX264,
		title:  "Movie",
		year:   2025,
		group:  "GROUP",
	},
	{
		name:       "Telesync spelled out",
		input:      "Movie.2025.720p.Telesync.x264-GROUP",
		resolution: Resolution720p,
		source:     SourceTelesync,
		codec:      CodecX264,
		title:      "Movie",
		year:       2025,
		group:      "GROUP",
	},

	// === Codec Variants (10 cases) ===
	{
		name:       "x264 lowercase",
		input:      "Miss.Marple.A.Caribbean.Mystery.1989.1080p.BluRay.x264-YELLOWBiRD.[NO.RAR]",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		title:      "Miss Marple A Caribbean Mystery",
		year:       1989,
		// NOTE: Group extraction stops at extra periods in suffix like [NO.RAR]
		group: "YELLOWBiRD.[NO",
	},
	{
		name:       "x265 standard",
		input:      "Teenage.Mutant.Ninja.Turtles.Out.of.the.Shadows.2016.1080p.BDRip.DDP7.1.x265-Vialle",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Teenage Mutant Ninja Turtles Out of the Shadows",
		year:       2016,
		group:      "Vialle",
	},
	{
		name:       "H.264 with dot separator",
		input:      "The.Sum.of.All.Fears.2002.1080p.iP.WEB-DL.AAC.2.0.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAAC,
		title:      "The Sum of All Fears",
		year:       2002,
		group:      "PiRaTeS",
	},
	{
		name:       "H.265 with dot separator",
		input:      "Tron.Ares.2025.IMAX.2160p.DSNP.WEB-DL.TrueHD.Atmos.7.1.DV.HDR.H.265-FLUX",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		edition:    "IMAX",
		title:      "Tron Ares",
		year:       2025,
		group:      "FLUX",
		service:    "Disney+",
	},
	{
		name:       "HEVC uppercase",
		input:      "Locked.2025.REPACK.UHD.BluRay.2160p.DTS-HD.MA.5.1.HEVC.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Locked",
		year:       2025,
		group:      "FraMeSToR",
		repack:     true,
	},
	{
		name:       "AVC codec (H.264 equivalent)",
		input:      "Diabolique.1996.1080p.BluRay.REMUX.AVC.FLAC.2.0-maniac",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioFLAC,
		isRemux:    true,
		title:      "Diabolique",
		year:       1996,
		group:      "maniac",
	},
	{
		name:       "VC-1 codec (not x264/x265)",
		input:      "Rendition.2007.1080p.BluRay.REMUX.VC-1.DTS-HD.MA.7.1-EPSiLON",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecUnknown,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Rendition",
		year:       2007,
		group:      "EPSiLON",
	},
	{
		name:       "10bit H.265",
		input:      "Scooby-Doo.and.the.Samurai.Sword.2009.1080p.BluRay.DDP.5.1.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Scooby-Doo and the Samurai Sword",
		year:       2009,
		group:      "iVy",
	},
	{
		name:       "HEVC-PSA group style",
		input:      "Charlies.Angels.2019.1080p.WEBRip.6CH.x265.HEVC-PSA",
		resolution: Resolution1080p,
		source:     SourceWEBRip,
		codec:      CodecX265,
		title:      "Charlies Angels",
		year:       2019,
		group:      "PSA",
	},
	{
		name:  "DoVi with x265",
		input: "The.Pink.Panther.Strikes.Again.1976.1080p.UHD.BluRay.FLAC2.0.DoVi.HDR10.x265-PTer",
		// NOTE: UHD in name triggers 2160p detection even with explicit 1080p
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		// DoVi detected and takes priority over HDR10 (DV releases often have HDR fallback layers)
		hdr:   DolbyVision,
		audio: AudioFLAC,
		title: "The Pink Panther Strikes Again",
		year:  1976,
		group: "PTer",
	},

	// === HDR Variants (15 cases) ===
	{
		name:       "HDR generic",
		input:      "The.Zone.of.Interest.2023.UHD.BluRay.2160p.DDP.Atmos.5.1.HDR.x265-hallowed",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        HDRGeneric,
		audio:      AudioAtmos,
		title:      "The Zone of Interest",
		year:       2023,
		group:      "hallowed",
	},
	{
		name:       "HDR10",
		input:      "Heat.1995.REPACK.UHD.BluRay.2160p.DDP.5.1.HDR.x265-hallowed",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        HDRGeneric,
		audio:      AudioEAC3,
		title:      "Heat",
		year:       1995,
		group:      "hallowed",
		repack:     true,
	},
	{
		name:       "HDR10+ with plus sign",
		input:      "Heretic.2024.REPACK.UHD.BluRay.2160p.DDP.Atmos.5.1.DV.HDR10+.x265-hallowed",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Heretic",
		year:       2024,
		group:      "hallowed",
		repack:     true,
	},
	{
		name:       "HDR10Plus spelled out",
		input:      "Zootopia.2016.2160p.DSNP.WEB-DL.TrueHD.7.1.Atmos.DV.HDR10Plus.H.265-Kitsune",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Zootopia",
		year:       2016,
		group:      "Kitsune",
		service:    "Disney+",
	},
	{
		name:       "DV only",
		input:      "La.Venue.de.l.avenir.2025.FRENCH.2160p.HDR.DV.WEB-DL.H.265-Slay3R",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		title:      "La Venue de l avenir",
		year:       2025,
		group:      "Slay3R",
	},
	{
		name:       "Dolby Vision spelled out",
		input:      "The.Rip.2026.MULTi.AD.1080p.NF.WEB.DV.HDR.H265-THESYNDiCATE",
		resolution: Resolution1080p,
		codec:      CodecX265,
		hdr:        DolbyVision,
		title:      "The Rip",
		year:       2026,
		group:      "THESYNDiCATE",
		service:    "Netflix",
	},
	{
		name:       "DV with HDR combo",
		input:      "End.of.Watch.2012.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HDR10P.HEVC.HYBRID.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "End of Watch",
		year:       2012,
		group:      "FraMeSToR",
	},
	{
		name:       "DoVi HDR10 combo",
		input:      "Crouching.Tiger.Hidden.Dragon.2000.2160p.UHD.BluRay.TrueHD.Atmos.7.1.DoVi.HDR.x265-PTer",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		// DoVi detected and takes priority over generic HDR (DV releases often have HDR fallback layers)
		hdr:   DolbyVision,
		audio: AudioAtmos,
		title: "Crouching Tiger Hidden Dragon",
		year:  2000,
		group: "PTer",
	},
	{
		name:       "DV HDR10+ combo",
		input:      "Now.You.See.Me.Now.You.Dont.2025.2160p.iT.WEB-DL.HDR10+.Atmos.DDP5.1-UBWEB",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		hdr:        HDR10Plus,
		audio:      AudioAtmos,
		title:      "Now You See Me Now You Dont",
		year:       2025,
		group:      "UBWEB",
		// NOTE: Service detection flaky - both ".now." and ".it." match in the name
		// Result depends on map iteration order, so we skip this check
		// service: either "NOW" or "iT"
	},
	{
		name:       "SDR explicit",
		input:      "The.Secret.Agent.2025.2160p.DCP.WEBRIP.AC3.SDR.H265-AOC",
		resolution: Resolution2160p,
		source:     SourceWEBRip,
		codec:      CodecX265,
		hdr:        HDRNone,
		audio:      AudioAC3,
		title:      "The Secret Agent",
		year:       2025,
		group:      "AOC",
	},
	{
		name:       "Hybrid DV HDR10",
		input:      "Pillion.2025.REPACK.2160p.iT.WEB-DL.Hybrid.H265.DV.HDR10.DDP.5.1.English-HONE",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioEAC3,
		title:      "Pillion",
		year:       2025,
		group:      "HONE",
		service:    "iT",
		repack:     true,
	},
	{
		name:       "HDR in middle",
		input:      "All.the.Devils.Are.Here.2025.2160p.SKST.WEB-DL.DD+5.1.HDR.H.265-playWEB",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        HDRGeneric,
		audio:      AudioEAC3,
		title:      "All the Devils Are Here",
		year:       2025,
		group:      "playWEB",
	},
	{
		name:       "DV-HDR10 with hyphen",
		input:      "Pi.1998.UHD.BluRay.DV-HDR10.10bit.2160p.AC-3.TrueHD7.1.Atmos.HEVC-d3g",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Pi",
		year:       1998,
		group:      "d3g",
	},
	{
		name:       "HDR10P shorthand",
		input:      "Tron.Ares.2025.Hybrid.2160p.UHD.Blu-ray.Remux.DV.HDR10P.HEVC.TrueHD.Atmos.7.1-CiNEPHiLES",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		isRemux:    true,
		title:      "Tron Ares",
		year:       2025,
		group:      "CiNEPHiLES",
	},
	{
		name:       "No HDR indicators",
		input:      "The.Zone.of.Interest.2023.BluRay.1080p.DDP.5.1.x264-hallowed",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		hdr:        HDRNone,
		audio:      AudioEAC3,
		title:      "The Zone of Interest",
		year:       2023,
		group:      "hallowed",
	},

	// === Audio Variants (15 cases) ===
	{
		name:       "Atmos with TrueHD",
		input:      "Wicked.2024.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		isRemux:    true,
		title:      "Wicked",
		year:       2024,
		group:      "FraMeSToR",
	},
	{
		name:       "Atmos with DDP",
		input:      "Day.Shift.2022.1080p.NF.WEB-DL.DDP.5.1.Atmos.H.264-CHDWEB",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAtmos,
		title:      "Day Shift",
		year:       2022,
		group:      "CHDWEB",
		service:    "Netflix",
	},
	{
		name:       "TrueHD without Atmos",
		input:      "The.Yellow.Taboo.2025.BluRay.1080p.AVC.TrueHD5.1-MTeam",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioTrueHD,
		title:      "The Yellow Taboo",
		year:       2025,
		group:      "MTeam",
	},
	{
		name:       "DTS-HD MA",
		input:      "Krrish.2006.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-EPSiLON",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Krrish",
		year:       2006,
		group:      "EPSiLON",
	},
	{
		name:       "DTS-HD with space",
		input:      "A.Hero.Never.Dies.1998.CHN.Bluray.1080p.x264.2Audios.DTS-HD.MA.5.1-BtsHD",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		title:      "A Hero Never Dies",
		year:       1998,
		group:      "BtsHD",
	},
	{
		name:       "Plain DTS",
		input:      "Patriots.Day.2016.BluRay.1080p.DTS-X.7.1.x264.dxva-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTS,
		title:      "Patriots Day",
		year:       2016,
		group:      "FraMeSToR",
	},
	{
		name:       "DDP with plus sign",
		input:      "The.Substance.2024.1080p.BluRay.DD+5.1.x264-PTer",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "The Substance",
		year:       2024,
		group:      "PTer",
	},
	{
		name:       "DDP abbreviated",
		input:      "Destined.At.Christmas.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Destined At Christmas",
		year:       2022,
		group:      "NTb",
		service:    "Amazon",
	},
	{
		name:       "EAC3",
		input:      "Dalloway.2025.FRENCH.1080p.WEBrip.10.bits.EAC3.5.1.x265-TyHD",
		resolution: Resolution1080p,
		source:     SourceWEBRip,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Dalloway",
		year:       2025,
		group:      "TyHD",
	},
	{
		name:       "DD5.1 (Dolby Digital)",
		input:      "Oceans.Twelve.2004.1080p.BluRay.REMUX.VC-1.DD5.1-EPSiLON",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		audio:      AudioAC3,
		isRemux:    true,
		title:      "Oceans Twelve",
		year:       2004,
		group:      "EPSiLON",
	},
	{
		name:       "AC3",
		input:      "A.Hero.Never.Dies.1998.CHN.Bluray.720p.x264.2Audios.AC3-BtsHD",
		resolution: Resolution720p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioAC3,
		title:      "A Hero Never Dies",
		year:       1998,
		group:      "BtsHD",
	},
	{
		name:       "FLAC lossless",
		input:      "The.Music.Room.1958.BluRay.1080p.FLAC.1.0.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioFLAC,
		isRemux:    true,
		title:      "The Music Room",
		year:       1958,
		group:      "FraMeSToR",
	},
	{
		name:       "AAC",
		input:      "Bambola.1996.1080p.WEB-DL.AAC.2.0.H.264-KUCHU",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAAC,
		title:      "Bambola",
		year:       1996,
		group:      "KUCHU",
	},
	{
		name:       "Opus",
		input:      "High.Test.Girls.1980.English.Dub.1080p.BluRay.HEVC-HQ.x265.Opus.5.1-TintoBrASS",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioOpus,
		title:      "High Test Girls",
		year:       1980,
		group:      "TintoBrASS",
	},
	{
		name:       "LPCM (not mapped)",
		input:      "Kummatty.1979.Yam.Daabo.1987.1080p.USA.Blu-ray.AVC.LPCM.1.0-TMT",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioUnknown,
		title:      "Kummatty",
		year:       1979,
		group:      "TMT",
	},

	// === Remux Patterns (10 cases) ===
	{
		name:       "REMUX uppercase",
		input:      "The.Taking.2014.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "The Taking",
		year:       2014,
		group:      "FraMeSToR",
	},
	{
		name:       "Remux mixed case",
		input:      "Fandango.1985.1080p.Blu-ray.Remux.AVC.DTS-HD.MA.5.1-SiCFoI",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Fandango",
		year:       1985,
		group:      "SiCFoI",
	},
	{
		name:       "UHD BluRay Remux",
		input:      "Adaptation.2002.UHD.BluRay.2160p.TrueHD.Atmos.7.1.DV.HEVC.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		isRemux:    true,
		title:      "Adaptation",
		year:       2002,
		group:      "FraMeSToR",
	},
	{
		name:       "Remux with Hybrid tag",
		input:      "The.Visit.2015.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.HYBRID.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "The Visit",
		year:       2015,
		group:      "FraMeSToR",
	},
	{
		name:       "BDRemux variant",
		input:      "Kingdom.of.the.Planet.of.the.Apes.2024.1080p.BluRay.REMUX.DD5.1.AVC-d3g",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioAC3,
		isRemux:    true,
		title:      "Kingdom of the Planet of the Apes",
		year:       2024,
		group:      "d3g",
	},
	{
		name:       "Remux with VC-1",
		input:      "Oceans.Thirteen.2007.1080p.BluRay.REMUX.VC-1.DD5.1-EPSiLON",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		audio:      AudioAC3,
		isRemux:    true,
		title:      "Oceans Thirteen",
		year:       2007,
		group:      "EPSiLON",
	},
	{
		name:       "Korean Remux",
		input:      "Love.in.the.Big.City.2024.KOR.BluRay.1080p.REMUX.AVC.DTS-HD.MA.5.1-UBits",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Love in the Big City",
		year:       2024,
		group:      "UBits",
	},
	{
		name:       "Remux with Dts-HDMa style",
		input:      "Star.Trek.Into.Darkness.2013.1080p.BluRay.Dts-HDMa5.1.AVC-d3g",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		title:      "Star Trek Into Darkness",
		year:       2013,
		group:      "d3g",
	},
	{
		name:       "Complete UHD Blu-ray (not encode)",
		input:      "Tank.Girl.1995.2160p.Complete.UHD.Blu-ray.DV.HDR.HEVC.DTS-HD.MA.5.1-BLoz",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		title:      "Tank Girl",
		year:       1995,
		group:      "BLoz",
	},
	{
		name:       "Not a remux (encode)",
		input:      "Ant-Man.2015.UHD.BluRay.2160p.DDP.7.1.DV.HDR.x265-hallowed",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioEAC3,
		isRemux:    false,
		title:      "Ant-Man",
		year:       2015,
		group:      "hallowed",
	},

	// === Edition Patterns (15 cases) ===
	{
		name:       "Directors Cut",
		input:      "1408.2007.Directors.Cut.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.TrueHD.5.1-CiNEPHiLES",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioTrueHD,
		isRemux:    true,
		edition:    "Directors Cut",
		title:      "1408",
		year:       2007,
		group:      "CiNEPHiLES",
	},
	{
		name:       "IMAX edition",
		input:      "Wonder.Woman.1984.2020.IMAX.2160p.MA.WEB-DL.TrueHD.Atmos.7.1.DV.HDR10P.H.265-TheFarm",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		edition:    "IMAX",
		// NOTE: Parser extracts first year match (1984 in title), not release year
		title: "Wonder Woman",
		year:  1984,
		group: "TheFarm",
	},
	{
		name:    "Extended Cut",
		input:   "Superhero.Movie.2008.Extended.Cut.BluRay.1080i.DTS-HD.MA.5.1.AVC.HYBRID.REMUX-FraMeSToR",
		source:  SourceBluRay,
		codec:   CodecX264,
		audio:   AudioDTSHD,
		isRemux: true,
		edition: "Extended",
		title:   "Superhero Movie",
		year:    2008,
		group:   "FraMeSToR",
	},
	{
		name:       "Theatrical Cut",
		input:      "Wild.Things.1998.Theatrical.Cut.UHD.BluRay.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		isRemux:    true,
		edition:    "Theatrical",
		title:      "Wild Things",
		year:       1998,
		group:      "FraMeSToR",
	},
	{
		name:       "Unrated edition",
		input:      "A.Nightmare.on.Elm.Street.1984.Uncut.REPACK.Hybrid.2160p.UHD.Remux.DV.HDR.HEVC.ATMOS.FLAC1.0-CiNEPHiLES",
		resolution: Resolution2160p,
		// NOTE: Hybrid not recognized as BluRay source
		// source:     SourceBluRay,
		codec:   CodecX265,
		hdr:     DolbyVision,
		audio:   AudioAtmos,
		isRemux: true,
		edition: "Uncut",
		title:   "A Nightmare on Elm Street",
		year:    1984,
		group:   "CiNEPHiLES",
		repack:  true,
	},
	{
		name:       "Remastered edition",
		input:      "Excalibur.1981.30th.Anniversary.Remaster.REMUX.1080p.Blu-ray.AVC.DTS-HD.MA.5.1-LEGi0N",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		edition:    "Anniversary",
		title:      "Excalibur",
		year:       1981,
		group:      "LEGi0N",
	},
	{
		name:       "Criterion Collection",
		input:      "Altered.States.1980.2160p.Criterion.Collection.USA.UHD.Blu-ray.DV.HDR.HEVC.DTS-HD.MA.5.1-LuckDIY",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		edition:    "Criterion",
		title:      "Altered States",
		year:       1980,
		group:      "LuckDIY",
	},
	{
		name:       "Extended with curly braces",
		input:      "G.I.Joe.Retaliation.2013.{edition-Extended}.1080p.BluRay.DDP.5.1.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		edition:    "Extended",
		title:      "G I Joe Retaliation",
		year:       2013,
		group:      "iVy",
	},
	{
		name:       "Directors Cut with curly braces",
		input:      "Brotherhood.of.the.Wolf.2001.{edition-Directors.Cut}.1080p.BluRay.DDP.5.1.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		edition:    "Directors Cut",
		title:      "Brotherhood of the Wolf",
		year:       2001,
		group:      "iVy",
	},
	{
		name:       "Theatrical with curly braces",
		input:      "Hancock.2008.{edition-Theatrical}.1080p.BluRay.DDP.5.1.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Hancock",
		year:       2008,
		group:      "iVy",
	},
	{
		name:       "Unrated with curly braces",
		input:      "Hancock.2008.{edition-Unrated}.1080p.BluRay.DDP.5.1.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Hancock",
		year:       2008,
		group:      "iVy",
	},
	{
		name:       "Remastered Directors Cut",
		input:      "Kingdom.of.Heaven.2005.Remastered.Directors.Cut.Complete.2160p.FRA.UHD.BluRay-P4RT4GE",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		edition:    "Remastered",
		title:      "Kingdom of Heaven",
		year:       2005,
		group:      "P4RT4GE",
	},
	{
		name:       "edition- style with hyphen",
		input:      "Zodiac.2007.edition-Directors.Cut.1080p.WEBRip.DDP.5.1.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceWEBRip,
		codec:      CodecX265,
		audio:      AudioEAC3,
		edition:    "Directors Cut",
		title:      "Zodiac",
		year:       2007,
		group:      "iVy",
	},
	{
		name:       "Restoration edition",
		input:      "Cannibal.The.Musical.1996.{edition-Restoration}.1080p.BluRay.DDP.2.0.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Cannibal The Musical",
		year:       1996,
		group:      "iVy",
	},
	{
		name:       "No edition",
		input:      "The.Matrix.1999.1080p.ATVP.MGMP.WEB-DL.DD.5.1.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		// NOTE: DD.5.1 not matched - parser looks for dd5, dd2, dd7 without preceding dot
		// audio:      AudioAC3,
		edition: "",
		title:   "The Matrix",
		year:    1999,
		group:   "PiRaTeS",
		service: "Apple TV+",
	},

	// === Streaming Services (10 cases) ===
	{
		name:       "Netflix NF",
		input:      "The.Rip.2026.2160p.NF.WEB-DL.Hybrid.H.265.DV.HDR.DDP.Atmos.5.1.English-HONE",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "The Rip",
		year:       2026,
		group:      "HONE",
		service:    "Netflix",
	},
	{
		name:       "Amazon AMZN",
		input:      "Double.Holiday.2019.1080p.AMZN.WEB-DL.DDP2.0.H.264-FLUX",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Double Holiday",
		year:       2019,
		group:      "FLUX",
		service:    "Amazon",
	},
	{
		name:       "Disney+ DSNP",
		input:      "Dashing.Through.the.Snow.2023.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.HDR.H.265-FLUX",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Dashing Through the Snow",
		year:       2023,
		group:      "FLUX",
		service:    "Disney+",
	},
	{
		name:       "Apple TV+ ATVP",
		input:      "Severance.S01E01.2022.1080p.ATVP.WEB-DL.DDP5.1.H.264-NTb",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Severance",
		year:       2022,
		group:      "NTb",
		service:    "Apple TV+",
	},
	{
		name:       "HBO Max HMAX",
		input:      "8.2025.1080p.HMAX.WEB-DL.DD+5.1.H.264-playWEB",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "8",
		year:       2025,
		group:      "playWEB",
		service:    "HBO Max",
	},
	{
		name:       "Peacock PCOK",
		input:      "The.Shawshank.Redemption.1994.1080p.PCOK.WEB-DL.DDP.5.1.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "The Shawshank Redemption",
		year:       1994,
		group:      "PiRaTeS",
		service:    "Peacock",
	},
	{
		name:       "Paramount+ PMTP",
		input:      "From.Dusk.Till.Dawn.1996.2160p.PMTP.WEB-DL.DTS-HD.MA.5.1.DV.HDR.H.265-FLUX",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioDTSHD,
		title:      "From Dusk Till Dawn",
		year:       1996,
		group:      "FLUX",
		service:    "Paramount+",
	},
	{
		name:       "Hulu service",
		input:      "Movie.2024.1080p.HULU.WEB-DL.DDP5.1.H.264-GROUP",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Movie",
		year:       2024,
		group:      "GROUP",
		service:    "Hulu",
	},
	{
		name:       "iTunes iT",
		input:      "Killer.Whale.2026.2160p.iTunes.WEB-DL.HEVC.10bit.DV.DD5.1.2Audios-QHstudIo",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAC3,
		title:      "Killer Whale",
		year:       2026,
		group:      "QHstudIo",
		// NOTE: "iTunes" not matched - parser looks for ".it." not ".itunes."
		// service:    "iT",
	},
	{
		name:       "No service identifier",
		input:      "Movie.2024.1080p.WEB-DL.DDP5.1.H.264-GROUP",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Movie",
		year:       2024,
		group:      "GROUP",
		service:    "",
	},

	// === Tricky Titles (15 cases) ===
	{
		name:       "Year at start of title",
		input:      "2001.A.Space.Odyssey.1968.1080p.BluRay.x264-GROUP",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		// NOTE: Parser matches first year-like number (2001), resulting in empty title
		title: "",
		year:  2001,
		group: "GROUP",
	},
	{
		name:       "Number in title",
		input:      "28.Years.Later.2025.1080p.BluRay.TrueHD.7.1.Atmos.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioAtmos,
		title:      "28 Years Later",
		year:       2025,
		group:      "iVy",
	},
	{
		name:       "Sequel number II",
		input:      "Teenage.Mutant.Ninja.Turtles.II.1991.1080p.BDRip.DDP5.1.x265-Vialle",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Teenage Mutant Ninja Turtles II",
		year:       1991,
		group:      "Vialle",
	},
	{
		name:       "Sequel number III",
		input:      "Teenage.Mutant.Ninja.Turtles.III.1993.1080p.BDRip.DDP5.1.x265-Vialle",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Teenage Mutant Ninja Turtles III",
		year:       1993,
		group:      "Vialle",
	},
	{
		name:       "Sequel with 2",
		input:      "March.of.the.Penguins.2.The.Next.Step.2017.GBR.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "March of the Penguins 2 The Next Step",
		year:       2017,
		group:      "FraMeSToR",
	},
	{
		name:       "Single digit title",
		input:      "8.2025.1080p.HMAX.WEB-DL.DD+5.1.H.264-playWEB",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "8",
		year:       2025,
		group:      "playWEB",
		service:    "HBO Max",
	},
	{
		name:       "Hyphenated title",
		input:      "Spider-Man.2.2004.1080p.BluRay.TrueHD.7.1.Atmos.10bit.H.265-iVy",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioAtmos,
		title:      "Spider-Man 2",
		year:       2004,
		group:      "iVy",
	},
	{
		name:       "Title with apostrophe",
		input:      "Tyler.Perrys.Madeas.Tough.Love.2015.1080p.AMZN.WEB-DL.DDP5.1.H.264-FLUX",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Tyler Perrys Madeas Tough Love",
		year:       2015,
		group:      "FLUX",
		service:    "Amazon",
	},
	{
		name:       "Title starting with The",
		input:      "The.Godfather.1972.1080p.iP.WEB-DL.AAC.2.0.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAAC,
		title:      "The Godfather",
		year:       1972,
		group:      "PiRaTeS",
	},
	{
		name:       "Part 2 in title",
		input:      "The.Godfather.Part.II.1974.1080p.iP.WEB-DL.AAC.2.0.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAAC,
		title:      "The Godfather Part II",
		year:       1974,
		group:      "PiRaTeS",
	},
	{
		name:       "Subtitle with colon replacement",
		input:      "Kill.Bill.Vol.2.2004.2160p.GER.UHD.Blu-ray.DoVi.HDR10.HEVC.DTS-HD.MA.5.1-FULLBRUTALiTY",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		// DoVi detected and takes priority over HDR10 (DV releases often have HDR fallback layers)
		hdr:   DolbyVision,
		audio: AudioDTSHD,
		title: "Kill Bill Vol 2",
		year:  2004,
		group: "FULLBRUTALiTY",
	},
	{
		name:       "Roman numeral in title (IV)",
		input:      "Star.Trek.IV.The.Voyage.Home.1986.1080p.BluRay.Dts-HDMa5.1.AVC-d3g",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		title:      "Star Trek IV The Voyage Home",
		year:       1986,
		group:      "d3g",
	},
	{
		name:       "Mockingjay Part 2",
		input:      "The.Hunger.Games.Mockingjay.Part.2.2015.1080p.PCOK.WEB-DL.DDP.5.1.H.264-PiRaTeS",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "The Hunger Games Mockingjay Part 2",
		year:       2015,
		group:      "PiRaTeS",
		service:    "Peacock",
	},
	{
		name:       "Year-like number in title (1408)",
		input:      "1408.2007.2160p.UHD.Blu-ray.Remux.DV.HDR.HEVC.TrueHD.Atmos.7.1-CiNEPHiLES",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		isRemux:    true,
		title:      "1408",
		year:       2007,
		group:      "CiNEPHiLES",
	},
	{
		name:       "Lowercase release",
		input:      "the.hunger.games.2012.720p.web.h264-jff",
		resolution: Resolution720p,
		codec:      CodecX264,
		title:      "the hunger games",
		year:       2012,
		group:      "jff",
	},

	// === PROPER/REPACK flags ===
	{
		name:       "PROPER release",
		input:      "Bill.and.Teds.Bogus.Journey.1991.PROPER.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "Bill and Teds Bogus Journey",
		year:       1991,
		group:      "FraMeSToR",
		proper:     true,
	},
	{
		name:       "REPACK release",
		input:      "The.Day.the.Earth.Stood.Still.2008.REPACK.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioDTSHD,
		isRemux:    true,
		title:      "The Day the Earth Stood Still",
		year:       2008,
		group:      "FraMeSToR",
		repack:     true,
	},
	{
		name:       "REPACK 4K release",
		input:      "Heretic.2024.REPACK.UHD.BluRay.2160p.DDP.Atmos.5.1.DV.HDR10.x265-hallowed",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "Heretic",
		year:       2024,
		group:      "hallowed",
		repack:     true,
	},

	// === TV Series Multi-Episode ===
	{
		name:       "Multi-episode range S01E05-06",
		input:      "Breaking.Bad.S01E05-06.720p.BluRay.x264-DEMAND",
		resolution: Resolution720p,
		source:     SourceBluRay,
		codec:      CodecX264,
		title:      "Breaking Bad",
		group:      "DEMAND",
	},
	{
		name:       "Multi-episode sequential S01E05E06",
		input:      "Game.of.Thrones.S01E05E06.1080p.BluRay.x264-ROVERS",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		title:      "Game of Thrones",
		group:      "ROVERS",
	},
	{
		name:       "Alternate format 1x05",
		input:      "The.Simpsons.12x05.Episode.Title.720p.HDTV.x264-LOL",
		resolution: Resolution720p,
		source:     SourceHDTV,
		codec:      CodecX264,
		title:      "The Simpsons",
		group:      "LOL",
	},

	// === Season Packs ===
	{
		name:       "Full season pack",
		input:      "Stranger.Things.Season.01.1080p.NF.WEB-DL.DDP5.1.x264-NTb",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioEAC3,
		title:      "Stranger Things",
		group:      "NTb",
		service:    "Netflix",
	},
	{
		name:       "S01 pack no episodes",
		input:      "House.of.the.Dragon.S01.2160p.HMAX.WEB-DL.DDP5.1.Atmos.DV.H.265-FLUX",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		audio:      AudioAtmos,
		title:      "House of the Dragon",
		group:      "FLUX",
		service:    "HBO Max",
	},
	{
		name:       "Complete season pack",
		input:      "The.Office.US.Complete.Season.3.720p.BluRay.x264-DEMAND",
		resolution: Resolution720p,
		source:     SourceBluRay,
		codec:      CodecX264,
		title:      "The Office US",
		group:      "DEMAND",
	},

	// === Daily Shows ===
	{
		name:       "Daily show European date",
		input:      "Late.Night.16.01.2026.720p.HDTV.x264-SORNY",
		resolution: Resolution720p,
		source:     SourceHDTV,
		codec:      CodecX264,
		title:      "Late Night",
		group:      "SORNY",
	},
	{
		name:       "Daily show compact date",
		input:      "Tonight.Show.20260116.720p.HULU.WEB-DL.AAC2.0.H.264-TEPES",
		resolution: Resolution720p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		audio:      AudioAAC,
		title:      "Tonight Show",
		group:      "TEPES",
		service:    "Hulu",
	},

	// === Fixed Audio Patterns ===
	{
		name:       "DD.5.1 with dots (fixed)",
		input:      "The.Matrix.1999.1080p.BluRay.DD.5.1.x264-GRP",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioAC3,
		title:      "The Matrix",
		year:       1999,
		group:      "GRP",
	},

	// === Fixed HDR Patterns ===
	{
		name:       "DoVi variant (fixed)",
		input:      "Crouching.Tiger.Hidden.Dragon.2000.2160p.UHD.BluRay.DoVi.x265-PTer",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		hdr:        DolbyVision,
		title:      "Crouching Tiger Hidden Dragon",
		year:       2000,
		group:      "PTer",
	},

	// === Audio Pattern Variants (new cases) ===
	{
		name:       "DD.5.1 with dots",
		input:      "Movie.Name.2024.1080p.BluRay.DD.5.1.x264-GROUP",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioAC3,
		title:      "Movie Name",
		year:       2024,
		group:      "GROUP",
	},
	{
		name:       "DD5.1 no separator",
		input:      "Movie.Name.2024.1080p.BluRay.DD5.1.x264-GROUP",
		resolution: Resolution1080p,
		source:     SourceBluRay,
		codec:      CodecX264,
		audio:      AudioAC3,
		title:      "Movie Name",
		year:       2024,
		group:      "GROUP",
	},
	{
		name:       "DDP.5.1 with dots",
		input:      "Movie.Name.2024.1080p.WEB-DL.DDP.5.1.x265-GROUP",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		audio:      AudioEAC3,
		title:      "Movie Name",
		year:       2024,
		group:      "GROUP",
	},
	{
		name:       "TrueHD.Atmos with dot",
		input:      "Movie.Name.2024.2160p.UHD.BluRay.TrueHD.Atmos.x265-GROUP",
		resolution: Resolution2160p,
		source:     SourceBluRay,
		codec:      CodecX265,
		audio:      AudioAtmos,
		title:      "Movie Name",
		year:       2024,
		group:      "GROUP",
	},

	// === Service Pattern Variants (new cases) ===
	{
		name:       "DSNY service code",
		input:      "Movie.Name.2024.1080p.DSNY.WEB-DL.x264-GROUP",
		resolution: Resolution1080p,
		source:     SourceWEBDL,
		codec:      CodecX264,
		service:    "Disney+",
		title:      "Movie Name",
		year:       2024,
		group:      "GROUP",
	},
	{
		name:       "APTV service code",
		input:      "Movie.Name.2024.2160p.APTV.WEB-DL.DV.x265-GROUP",
		resolution: Resolution2160p,
		source:     SourceWEBDL,
		codec:      CodecX265,
		hdr:        DolbyVision,
		service:    "Apple TV+",
		title:      "Movie Name",
		year:       2024,
		group:      "GROUP",
	},
}

func TestParse_Golden(t *testing.T) {
	for _, tc := range goldenCases {
		t.Run(tc.name, func(t *testing.T) {
			info := Parse(tc.input)

			// Resolution - only check if expected is set
			if tc.resolution != ResolutionUnknown {
				assert.Equal(t, tc.resolution, info.Resolution, "resolution")
			}

			// Source - only check if expected is set
			if tc.source != SourceUnknown {
				assert.Equal(t, tc.source, info.Source, "source")
			}

			// Codec - only check if expected is set
			if tc.codec != CodecUnknown {
				assert.Equal(t, tc.codec, info.Codec, "codec")
			}

			// HDR - always check (HDRNone is a valid expected value)
			assert.Equal(t, tc.hdr, info.HDR, "hdr")

			// Audio - only check if expected is set
			if tc.audio != AudioUnknown {
				assert.Equal(t, tc.audio, info.Audio, "audio")
			}

			// IsRemux - always check
			assert.Equal(t, tc.isRemux, info.IsRemux, "isRemux")

			// Edition - only check if expected is set
			if tc.edition != "" {
				assert.Equal(t, tc.edition, info.Edition, "edition")
			}

			// Title - only check if expected is set
			if tc.title != "" {
				assert.Equal(t, tc.title, info.Title, "title")
			}

			// Year - only check if expected is set
			if tc.year != 0 {
				assert.Equal(t, tc.year, info.Year, "year")
			}

			// Group - only check if expected is set
			if tc.group != "" {
				assert.Equal(t, tc.group, info.Group, "group")
			}

			// Service - only check if expected is set
			if tc.service != "" {
				assert.Equal(t, tc.service, info.Service, "service")
			}

			// Proper - always check
			assert.Equal(t, tc.proper, info.Proper, "proper")

			// Repack - always check
			assert.Equal(t, tc.repack, info.Repack, "repack")
		})
	}
}
