// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmunix/arrgo/internal/search (interfaces: IndexerAPI)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/vmunix/arrgo/internal/search IndexerAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	search "github.com/vmunix/arrgo/internal/search"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexerAPI is a mock of IndexerAPI interface.
type MockIndexerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerAPIMockRecorder
	isgomock struct{}
}

// MockIndexerAPIMockRecorder is the mock recorder for MockIndexerAPI.
type MockIndexerAPIMockRecorder struct {
	mock *MockIndexerAPI
}

// NewMockIndexerAPI creates a new mock instance.
func NewMockIndexerAPI(ctrl *gomock.Controller) *MockIndexerAPI {
	mock := &MockIndexerAPI{ctrl: ctrl}
	mock.recorder = &MockIndexerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexerAPI) EXPECT() *MockIndexerAPIMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockIndexerAPI) Search(ctx context.Context, q search.Query) ([]search.Release, []error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, q)
	ret0, _ := ret[0].([]search.Release)
	ret1, _ := ret[1].([]error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIndexerAPIMockRecorder) Search(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIndexerAPI)(nil).Search), ctx, q)
}
